export interface BusinessSection {
  id: string;
  title: string;
  type: "hero" | "services" | "products" | "schedule" | "gallery" | "testimonials" | "about" | "menu" | "events" | "pricing" | "team" | "contact" | "faq" | "cta" | "features" | "portfolio" | "booking";
  required: boolean;
}

export interface BusinessCategory {
  id: string;
  label: string;
  labelPt: string;
  icon: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  gradient: string;
  tone: "professional" | "friendly" | "luxury" | "spiritual" | "energetic" | "relaxing" | "fun" | "serious";
  sections: BusinessSection[];
  defaultServices: string[];
  defaultCTAs: string[];
  imageStyle: string;
  keywords: string[];
}

export const businessCategories: BusinessCategory[] = [
  {
    id: "church",
    label: "Church",
    labelPt: "Igreja",
    icon: "Church",
    primaryColor: "#6366F1",
    secondaryColor: "#A78BFA",
    accentColor: "#F59E0B",
    gradient: "from-indigo-600 to-purple-600",
    tone: "spiritual",
    sections: [
      { id: "hero", title: "Bem-vindo", type: "hero", required: true },
      { id: "schedule", title: "Horários de Cultos", type: "schedule", required: true },
      { id: "about", title: "Nossa História", type: "about", required: true },
      { id: "events", title: "Agenda de Eventos", type: "events", required: false },
      { id: "team", title: "Liderança", type: "team", required: false },
      { id: "contact", title: "Contato", type: "contact", required: true },
    ],
    defaultServices: ["Culto de Celebração", "Escola Bíblica", "Grupo de Jovens", "Ministério Infantil"],
    defaultCTAs: ["Visite-nos", "Pedido de Oração", "Assistir Online"],
    imageStyle: "interior de igreja iluminado, altar, vitrais, ambiente acolhedor e espiritual",
    keywords: ["fé", "comunidade", "esperança", "amor", "família"],
  },
  {
    id: "candy_store",
    label: "Candy Store",
    labelPt: "Loja de Doces",
    icon: "Candy",
    primaryColor: "#EC4899",
    secondaryColor: "#F472B6",
    accentColor: "#FCD34D",
    gradient: "from-pink-500 to-rose-500",
    tone: "fun",
    sections: [
      { id: "hero", title: "Doces Irresistíveis", type: "hero", required: true },
      { id: "products", title: "Nossos Doces", type: "products", required: true },
      { id: "features", title: "Por que Escolher", type: "features", required: false },
      { id: "gallery", title: "Galeria", type: "gallery", required: false },
      { id: "pricing", title: "Kits para Festa", type: "pricing", required: false },
      { id: "contact", title: "Encomendas", type: "contact", required: true },
    ],
    defaultServices: ["Brigadeiros Gourmet", "Bolos Decorados", "Kits para Festa", "Doces Finos"],
    defaultCTAs: ["Fazer Encomenda", "Ver Cardápio", "WhatsApp"],
    imageStyle: "vitrine colorida de doces, brigadeiros, bolos decorados, ambiente alegre e colorido",
    keywords: ["doces", "festas", "encomendas", "sabor", "celebração"],
  },
  {
    id: "clothing_store",
    label: "Clothing Store",
    labelPt: "Loja de Roupas",
    icon: "Shirt",
    primaryColor: "#0EA5E9",
    secondaryColor: "#38BDF8",
    accentColor: "#F97316",
    gradient: "from-sky-500 to-blue-600",
    tone: "friendly",
    sections: [
      { id: "hero", title: "Nova Coleção", type: "hero", required: true },
      { id: "products", title: "Destaques", type: "products", required: true },
      { id: "gallery", title: "Lookbook", type: "gallery", required: true },
      { id: "features", title: "Diferenciais", type: "features", required: false },
      { id: "about", title: "Nossa Loja", type: "about", required: false },
      { id: "contact", title: "Visite-nos", type: "contact", required: true },
    ],
    defaultServices: ["Moda Feminina", "Moda Masculina", "Acessórios", "Calçados"],
    defaultCTAs: ["Ver Coleção", "Novidades", "WhatsApp"],
    imageStyle: "loja de roupas moderna, araras organizadas, provador, ambiente fashion e iluminado",
    keywords: ["moda", "estilo", "tendências", "looks", "novidades"],
  },
  {
    id: "bar",
    label: "Bar",
    labelPt: "Bar",
    icon: "Beer",
    primaryColor: "#F59E0B",
    secondaryColor: "#FBBF24",
    accentColor: "#EF4444",
    gradient: "from-amber-500 to-orange-600",
    tone: "energetic",
    sections: [
      { id: "hero", title: "O Melhor da Noite", type: "hero", required: true },
      { id: "menu", title: "Cardápio de Drinks", type: "menu", required: true },
      { id: "events", title: "Programação", type: "events", required: true },
      { id: "gallery", title: "Ambiente", type: "gallery", required: false },
      { id: "features", title: "Happy Hour", type: "features", required: false },
      { id: "contact", title: "Reservas", type: "contact", required: true },
    ],
    defaultServices: ["Drinks Artesanais", "Cervejas Especiais", "Petiscos", "Música ao Vivo"],
    defaultCTAs: ["Reservar Mesa", "Ver Cardápio", "Happy Hour"],
    imageStyle: "bar moderno, balcão com drinks coloridos, ambiente noturno, iluminação neon",
    keywords: ["drinks", "noite", "amigos", "música", "diversão"],
  },
  {
    id: "nail_salon",
    label: "Nail Salon",
    labelPt: "Manicure",
    icon: "Paintbrush",
    primaryColor: "#E91E8C",
    secondaryColor: "#F472B6",
    accentColor: "#A855F7",
    gradient: "from-pink-500 to-fuchsia-600",
    tone: "luxury",
    sections: [
      { id: "hero", title: "Unhas Perfeitas", type: "hero", required: true },
      { id: "services", title: "Serviços", type: "services", required: true },
      { id: "portfolio", title: "Portfólio", type: "portfolio", required: true },
      { id: "pricing", title: "Tabela de Preços", type: "pricing", required: true },
      { id: "booking", title: "Agendamento", type: "booking", required: true },
      { id: "contact", title: "Contato", type: "contact", required: true },
    ],
    defaultServices: ["Manicure Tradicional", "Unhas em Gel", "Nail Art", "Esmaltação em Gel"],
    defaultCTAs: ["Agendar Horário", "Ver Portfólio", "WhatsApp"],
    imageStyle: "unhas decoradas profissionais, esmaltes coloridos, ambiente clean de salão",
    keywords: ["unhas", "beleza", "cuidados", "nail art", "gel"],
  },
  {
    id: "massage",
    label: "Massage Therapy",
    labelPt: "Massagem",
    icon: "Heart",
    primaryColor: "#10B981",
    secondaryColor: "#34D399",
    accentColor: "#8B5CF6",
    gradient: "from-emerald-500 to-teal-600",
    tone: "relaxing",
    sections: [
      { id: "hero", title: "Relaxe e Renove", type: "hero", required: true },
      { id: "services", title: "Tipos de Massagem", type: "services", required: true },
      { id: "features", title: "Benefícios", type: "features", required: true },
      { id: "pricing", title: "Pacotes", type: "pricing", required: false },
      { id: "gallery", title: "Nosso Espaço", type: "gallery", required: false },
      { id: "booking", title: "Agende sua Sessão", type: "booking", required: true },
    ],
    defaultServices: ["Massagem Relaxante", "Massagem Terapêutica", "Drenagem Linfática", "Reflexologia"],
    defaultCTAs: ["Agendar Sessão", "Ver Pacotes", "WhatsApp"],
    imageStyle: "ambiente spa relaxante, velas, toalhas, óleos essenciais, natureza",
    keywords: ["relaxamento", "bem-estar", "saúde", "terapia", "paz"],
  },
  {
    id: "concert_venue",
    label: "Concert Venue",
    labelPt: "Casa de Shows",
    icon: "Music",
    primaryColor: "#7C3AED",
    secondaryColor: "#A78BFA",
    accentColor: "#F59E0B",
    gradient: "from-violet-600 to-purple-700",
    tone: "energetic",
    sections: [
      { id: "hero", title: "Experiências Únicas", type: "hero", required: true },
      { id: "events", title: "Próximos Shows", type: "events", required: true },
      { id: "gallery", title: "Galeria de Fotos", type: "gallery", required: true },
      { id: "features", title: "Estrutura", type: "features", required: false },
      { id: "pricing", title: "Área VIP", type: "pricing", required: false },
      { id: "contact", title: "Ingressos e Contato", type: "contact", required: true },
    ],
    defaultServices: ["Shows ao Vivo", "Área VIP", "Bar Completo", "Estacionamento"],
    defaultCTAs: ["Ver Agenda", "Comprar Ingressos", "Reservar VIP"],
    imageStyle: "palco com luzes coloridas, multidão animada, show ao vivo, equipamento de som",
    keywords: ["shows", "música", "eventos", "noite", "diversão"],
  },
  {
    id: "restaurant",
    label: "Restaurant",
    labelPt: "Restaurante",
    icon: "UtensilsCrossed",
    primaryColor: "#DC2626",
    secondaryColor: "#EF4444",
    accentColor: "#FCD34D",
    gradient: "from-red-600 to-orange-600",
    tone: "friendly",
    sections: [
      { id: "hero", title: "Sabores Inesquecíveis", type: "hero", required: true },
      { id: "menu", title: "Cardápio", type: "menu", required: true },
      { id: "features", title: "Especialidades", type: "features", required: false },
      { id: "gallery", title: "Ambiente", type: "gallery", required: false },
      { id: "testimonials", title: "Avaliações", type: "testimonials", required: false },
      { id: "contact", title: "Reservas", type: "contact", required: true },
    ],
    defaultServices: ["Almoço Executivo", "Jantar", "Delivery", "Eventos Privativos"],
    defaultCTAs: ["Ver Cardápio", "Fazer Reserva", "Pedir Delivery"],
    imageStyle: "pratos gourmet, ambiente de restaurante aconchegante, mesa posta, comida apetitosa",
    keywords: ["gastronomia", "sabor", "chef", "experiência", "reserva"],
  },
  {
    id: "burger_joint",
    label: "Burger Joint",
    labelPt: "Hamburgueria",
    icon: "Beef",
    primaryColor: "#FF6B35",
    secondaryColor: "#FF8C42",
    accentColor: "#FFD166",
    gradient: "from-orange-500 to-red-600",
    tone: "fun",
    sections: [
      { id: "hero", title: "Hambúrgueres Artesanais", type: "hero", required: true },
      { id: "menu", title: "Nosso Cardápio", type: "menu", required: true },
      { id: "products", title: "Combos", type: "products", required: true },
      { id: "features", title: "Diferenciais", type: "features", required: false },
      { id: "gallery", title: "Galeria", type: "gallery", required: false },
      { id: "contact", title: "Delivery", type: "contact", required: true },
    ],
    defaultServices: ["Hambúrgueres Artesanais", "Batatas Especiais", "Milk Shakes", "Combos"],
    defaultCTAs: ["Pedir Agora", "Ver Cardápio", "Delivery WhatsApp"],
    imageStyle: "hambúrguer artesanal suculento, batatas fritas, ambiente descontraído, fast food premium",
    keywords: ["hambúrguer", "artesanal", "combo", "delivery", "sabor"],
  },
  {
    id: "bakery",
    label: "Bakery",
    labelPt: "Padaria",
    icon: "Croissant",
    primaryColor: "#D97706",
    secondaryColor: "#F59E0B",
    accentColor: "#FBBF24",
    gradient: "from-amber-600 to-yellow-500",
    tone: "friendly",
    sections: [
      { id: "hero", title: "Pães Fresquinhos", type: "hero", required: true },
      { id: "products", title: "Nossos Produtos", type: "products", required: true },
      { id: "schedule", title: "Horários", type: "schedule", required: true },
      { id: "features", title: "Diferenciais", type: "features", required: false },
      { id: "gallery", title: "Galeria", type: "gallery", required: false },
      { id: "contact", title: "Encomendas", type: "contact", required: true },
    ],
    defaultServices: ["Pães Artesanais", "Bolos e Tortas", "Café da Manhã", "Salgados"],
    defaultCTAs: ["Encomendar", "Ver Produtos", "WhatsApp"],
    imageStyle: "pães frescos saindo do forno, vitrine de padaria, croissants, ambiente aconchegante",
    keywords: ["pão", "fresco", "artesanal", "café", "manhã"],
  },
  {
    id: "gym",
    label: "Gym",
    labelPt: "Academia",
    icon: "Dumbbell",
    primaryColor: "#EF4444",
    secondaryColor: "#F87171",
    accentColor: "#10B981",
    gradient: "from-red-500 to-orange-500",
    tone: "energetic",
    sections: [
      { id: "hero", title: "Transforme seu Corpo", type: "hero", required: true },
      { id: "services", title: "Modalidades", type: "services", required: true },
      { id: "pricing", title: "Planos", type: "pricing", required: true },
      { id: "team", title: "Profissionais", type: "team", required: false },
      { id: "gallery", title: "Estrutura", type: "gallery", required: false },
      { id: "contact", title: "Matricule-se", type: "contact", required: true },
    ],
    defaultServices: ["Musculação", "Funcional", "Spinning", "Personal Trainer"],
    defaultCTAs: ["Agende uma Aula", "Ver Planos", "Matricule-se"],
    imageStyle: "academia moderna com equipamentos, pessoas treinando, ambiente motivacional",
    keywords: ["fitness", "saúde", "treino", "força", "energia"],
  },
  {
    id: "beauty_salon",
    label: "Beauty Salon",
    labelPt: "Salão de Beleza",
    icon: "Scissors",
    primaryColor: "#E91E8C",
    secondaryColor: "#F472B6",
    accentColor: "#A855F7",
    gradient: "from-pink-500 to-purple-600",
    tone: "luxury",
    sections: [
      { id: "hero", title: "Beleza e Estilo", type: "hero", required: true },
      { id: "services", title: "Serviços", type: "services", required: true },
      { id: "portfolio", title: "Portfólio", type: "portfolio", required: true },
      { id: "team", title: "Profissionais", type: "team", required: false },
      { id: "pricing", title: "Tabela de Preços", type: "pricing", required: false },
      { id: "booking", title: "Agende seu Horário", type: "booking", required: true },
    ],
    defaultServices: ["Corte Feminino", "Coloração", "Tratamentos Capilares", "Penteados"],
    defaultCTAs: ["Agendar Horário", "Ver Serviços", "WhatsApp"],
    imageStyle: "salão de beleza elegante, cadeiras de cabeleireiro, espelhos, ambiente sofisticado",
    keywords: ["cabelo", "beleza", "estilo", "transformação", "cuidados"],
  },
  {
    id: "barbershop",
    label: "Barbershop",
    labelPt: "Barbearia",
    icon: "Scissors",
    primaryColor: "#1F2937",
    secondaryColor: "#374151",
    accentColor: "#F59E0B",
    gradient: "from-gray-800 to-gray-900",
    tone: "professional",
    sections: [
      { id: "hero", title: "Estilo Masculino", type: "hero", required: true },
      { id: "services", title: "Serviços", type: "services", required: true },
      { id: "portfolio", title: "Cortes", type: "portfolio", required: true },
      { id: "team", title: "Barbeiros", type: "team", required: false },
      { id: "pricing", title: "Valores", type: "pricing", required: false },
      { id: "booking", title: "Agende seu Horário", type: "booking", required: true },
    ],
    defaultServices: ["Corte Masculino", "Barba", "Pigmentação", "Combo Completo"],
    defaultCTAs: ["Agendar", "Ver Cortes", "WhatsApp"],
    imageStyle: "barbearia vintage, cadeira de barbeiro, navalha, ambiente masculino clássico",
    keywords: ["barba", "corte", "estilo", "homem", "cuidados"],
  },
  {
    id: "pet_shop",
    label: "Pet Shop",
    labelPt: "Pet Shop",
    icon: "PawPrint",
    primaryColor: "#22C55E",
    secondaryColor: "#4ADE80",
    accentColor: "#F97316",
    gradient: "from-green-500 to-emerald-600",
    tone: "friendly",
    sections: [
      { id: "hero", title: "Amor pelos Pets", type: "hero", required: true },
      { id: "services", title: "Serviços", type: "services", required: true },
      { id: "products", title: "Produtos", type: "products", required: true },
      { id: "gallery", title: "Galeria", type: "gallery", required: false },
      { id: "pricing", title: "Banho e Tosa", type: "pricing", required: false },
      { id: "contact", title: "Agende", type: "contact", required: true },
    ],
    defaultServices: ["Banho e Tosa", "Consulta Veterinária", "Ração e Acessórios", "Hotel para Pets"],
    defaultCTAs: ["Agendar Banho", "Ver Produtos", "WhatsApp"],
    imageStyle: "pet shop colorido, cachorro fofo sendo tosado, produtos para pets, ambiente alegre",
    keywords: ["pet", "cachorro", "gato", "cuidados", "amor"],
  },
  {
    id: "dental_clinic",
    label: "Dental Clinic",
    labelPt: "Clínica Odontológica",
    icon: "Stethoscope",
    primaryColor: "#0EA5E9",
    secondaryColor: "#38BDF8",
    accentColor: "#10B981",
    gradient: "from-sky-500 to-cyan-600",
    tone: "professional",
    sections: [
      { id: "hero", title: "Sorriso Perfeito", type: "hero", required: true },
      { id: "services", title: "Tratamentos", type: "services", required: true },
      { id: "team", title: "Especialistas", type: "team", required: true },
      { id: "features", title: "Diferenciais", type: "features", required: false },
      { id: "testimonials", title: "Depoimentos", type: "testimonials", required: false },
      { id: "booking", title: "Agende sua Consulta", type: "booking", required: true },
    ],
    defaultServices: ["Clareamento", "Implantes", "Ortodontia", "Limpeza"],
    defaultCTAs: ["Agendar Consulta", "Conheça Tratamentos", "WhatsApp"],
    imageStyle: "clínica odontológica moderna, equipamentos, dentista profissional, ambiente limpo",
    keywords: ["sorriso", "dentes", "saúde", "tratamento", "clínica"],
  },
  {
    id: "pharmacy",
    label: "Pharmacy",
    labelPt: "Farmácia",
    icon: "Pill",
    primaryColor: "#16A34A",
    secondaryColor: "#22C55E",
    accentColor: "#EF4444",
    gradient: "from-green-600 to-emerald-600",
    tone: "professional",
    sections: [
      { id: "hero", title: "Saúde e Bem-estar", type: "hero", required: true },
      { id: "services", title: "Serviços", type: "services", required: true },
      { id: "products", title: "Produtos", type: "products", required: false },
      { id: "features", title: "Diferenciais", type: "features", required: false },
      { id: "schedule", title: "Horário de Funcionamento", type: "schedule", required: true },
      { id: "contact", title: "Contato", type: "contact", required: true },
    ],
    defaultServices: ["Medicamentos", "Dermocosméticos", "Perfumaria", "Delivery"],
    defaultCTAs: ["Delivery", "Ver Ofertas", "WhatsApp"],
    imageStyle: "farmácia organizada, prateleiras de medicamentos, atendente profissional",
    keywords: ["saúde", "medicamentos", "bem-estar", "cuidados", "farmácia"],
  },
  {
    id: "car_wash",
    label: "Car Wash",
    labelPt: "Lava Rápido",
    icon: "Car",
    primaryColor: "#3B82F6",
    secondaryColor: "#60A5FA",
    accentColor: "#10B981",
    gradient: "from-blue-500 to-cyan-500",
    tone: "friendly",
    sections: [
      { id: "hero", title: "Brilho Garantido", type: "hero", required: true },
      { id: "services", title: "Serviços", type: "services", required: true },
      { id: "pricing", title: "Tabela de Preços", type: "pricing", required: true },
      { id: "features", title: "Diferenciais", type: "features", required: false },
      { id: "gallery", title: "Resultados", type: "gallery", required: false },
      { id: "contact", title: "Agende", type: "contact", required: true },
    ],
    defaultServices: ["Lavagem Simples", "Lavagem Completa", "Polimento", "Higienização Interna"],
    defaultCTAs: ["Agendar", "Ver Preços", "WhatsApp"],
    imageStyle: "lava rápido profissional, carro sendo lavado, jatos de água, ambiente limpo",
    keywords: ["carro", "limpeza", "brilho", "lavagem", "cuidados"],
  },
  {
    id: "auto_repair",
    label: "Auto Repair Shop",
    labelPt: "Oficina Mecânica",
    icon: "Wrench",
    primaryColor: "#4B5563",
    secondaryColor: "#6B7280",
    accentColor: "#F59E0B",
    gradient: "from-gray-600 to-gray-800",
    tone: "professional",
    sections: [
      { id: "hero", title: "Seu Carro em Boas Mãos", type: "hero", required: true },
      { id: "services", title: "Serviços", type: "services", required: true },
      { id: "features", title: "Garantias", type: "features", required: true },
      { id: "testimonials", title: "Clientes Satisfeitos", type: "testimonials", required: false },
      { id: "gallery", title: "Estrutura", type: "gallery", required: false },
      { id: "contact", title: "Orçamento", type: "contact", required: true },
    ],
    defaultServices: ["Revisão Completa", "Freios", "Suspensão", "Motor"],
    defaultCTAs: ["Solicitar Orçamento", "Ver Serviços", "WhatsApp"],
    imageStyle: "oficina mecânica organizada, ferramentas, carro no elevador, mecânico profissional",
    keywords: ["carro", "mecânica", "reparo", "manutenção", "confiança"],
  },
  {
    id: "real_estate",
    label: "Real Estate Agency",
    labelPt: "Imobiliária",
    icon: "Home",
    primaryColor: "#0284C7",
    secondaryColor: "#0EA5E9",
    accentColor: "#F59E0B",
    gradient: "from-sky-600 to-blue-700",
    tone: "professional",
    sections: [
      { id: "hero", title: "Seu Novo Lar", type: "hero", required: true },
      { id: "products", title: "Imóveis em Destaque", type: "products", required: true },
      { id: "services", title: "Serviços", type: "services", required: true },
      { id: "features", title: "Por que Nos Escolher", type: "features", required: false },
      { id: "team", title: "Corretores", type: "team", required: false },
      { id: "contact", title: "Fale Conosco", type: "contact", required: true },
    ],
    defaultServices: ["Venda de Imóveis", "Aluguel", "Avaliação", "Financiamento"],
    defaultCTAs: ["Ver Imóveis", "Falar com Corretor", "WhatsApp"],
    imageStyle: "casa moderna bonita, interior decorado, ambiente imobiliário profissional",
    keywords: ["imóvel", "casa", "apartamento", "compra", "venda"],
  },
  {
    id: "law_office",
    label: "Law Office",
    labelPt: "Escritório de Advocacia",
    icon: "Scale",
    primaryColor: "#1E3A5F",
    secondaryColor: "#2563EB",
    accentColor: "#D4AF37",
    gradient: "from-blue-900 to-blue-800",
    tone: "serious",
    sections: [
      { id: "hero", title: "Justiça e Excelência", type: "hero", required: true },
      { id: "services", title: "Áreas de Atuação", type: "services", required: true },
      { id: "team", title: "Advogados", type: "team", required: true },
      { id: "about", title: "O Escritório", type: "about", required: false },
      { id: "testimonials", title: "Casos de Sucesso", type: "testimonials", required: false },
      { id: "contact", title: "Consulta", type: "contact", required: true },
    ],
    defaultServices: ["Direito Civil", "Direito Trabalhista", "Direito Criminal", "Direito Empresarial"],
    defaultCTAs: ["Agendar Consulta", "Falar com Advogado", "WhatsApp"],
    imageStyle: "escritório de advocacia elegante, livros de direito, ambiente profissional sério",
    keywords: ["advocacia", "direito", "justiça", "consultoria", "processo"],
  },
  {
    id: "florist",
    label: "Florist",
    labelPt: "Floricultura",
    icon: "Flower2",
    primaryColor: "#EC4899",
    secondaryColor: "#F472B6",
    accentColor: "#22C55E",
    gradient: "from-pink-500 to-rose-600",
    tone: "friendly",
    sections: [
      { id: "hero", title: "Flores para Toda Ocasião", type: "hero", required: true },
      { id: "products", title: "Arranjos", type: "products", required: true },
      { id: "features", title: "Ocasiões", type: "features", required: false },
      { id: "gallery", title: "Galeria", type: "gallery", required: false },
      { id: "pricing", title: "Cestas e Combos", type: "pricing", required: false },
      { id: "contact", title: "Encomendas", type: "contact", required: true },
    ],
    defaultServices: ["Buquês", "Arranjos Decorativos", "Cestas de Flores", "Delivery"],
    defaultCTAs: ["Encomendar", "Ver Arranjos", "WhatsApp"],
    imageStyle: "floricultura colorida, arranjos de flores, buquês, ambiente floral perfumado",
    keywords: ["flores", "presente", "amor", "decoração", "natureza"],
  },
  {
    id: "photography",
    label: "Photography Studio",
    labelPt: "Estúdio Fotográfico",
    icon: "Camera",
    primaryColor: "#6366F1",
    secondaryColor: "#818CF8",
    accentColor: "#F59E0B",
    gradient: "from-indigo-600 to-violet-600",
    tone: "professional",
    sections: [
      { id: "hero", title: "Momentos Eternizados", type: "hero", required: true },
      { id: "portfolio", title: "Portfólio", type: "portfolio", required: true },
      { id: "services", title: "Serviços", type: "services", required: true },
      { id: "pricing", title: "Pacotes", type: "pricing", required: false },
      { id: "testimonials", title: "Clientes", type: "testimonials", required: false },
      { id: "booking", title: "Agende seu Ensaio", type: "booking", required: true },
    ],
    defaultServices: ["Ensaio Fotográfico", "Casamentos", "Eventos", "Fotos Corporativas"],
    defaultCTAs: ["Ver Portfólio", "Orçamento", "WhatsApp"],
    imageStyle: "estúdio fotográfico profissional, câmeras, flashes, ambiente criativo",
    keywords: ["foto", "memória", "casamento", "ensaio", "arte"],
  },
  {
    id: "tattoo_studio",
    label: "Tattoo Studio",
    labelPt: "Estúdio de Tatuagem",
    icon: "Palette",
    primaryColor: "#1F2937",
    secondaryColor: "#374151",
    accentColor: "#EF4444",
    gradient: "from-gray-900 to-gray-800",
    tone: "professional",
    sections: [
      { id: "hero", title: "Arte na Pele", type: "hero", required: true },
      { id: "portfolio", title: "Portfólio", type: "portfolio", required: true },
      { id: "services", title: "Estilos", type: "services", required: true },
      { id: "team", title: "Artistas", type: "team", required: false },
      { id: "faq", title: "Dúvidas Frequentes", type: "faq", required: false },
      { id: "booking", title: "Agende sua Sessão", type: "booking", required: true },
    ],
    defaultServices: ["Tatuagem Realista", "Old School", "Blackwork", "Cover Up"],
    defaultCTAs: ["Agendar", "Ver Trabalhos", "WhatsApp"],
    imageStyle: "estúdio de tatuagem, máquina de tattoo, desenhos, ambiente artístico dark",
    keywords: ["tatuagem", "arte", "desenho", "estilo", "personalidade"],
  },
  {
    id: "daycare",
    label: "Daycare Center",
    labelPt: "Creche / Escola Infantil",
    icon: "Baby",
    primaryColor: "#F59E0B",
    secondaryColor: "#FBBF24",
    accentColor: "#22C55E",
    gradient: "from-amber-400 to-orange-500",
    tone: "friendly",
    sections: [
      { id: "hero", title: "Cuidando do Futuro", type: "hero", required: true },
      { id: "services", title: "Atividades", type: "services", required: true },
      { id: "features", title: "Diferenciais", type: "features", required: true },
      { id: "team", title: "Equipe Pedagógica", type: "team", required: false },
      { id: "gallery", title: "Estrutura", type: "gallery", required: false },
      { id: "contact", title: "Matrícula", type: "contact", required: true },
    ],
    defaultServices: ["Berçário", "Educação Infantil", "Período Integral", "Alimentação Balanceada"],
    defaultCTAs: ["Agendar Visita", "Ver Estrutura", "WhatsApp"],
    imageStyle: "creche colorida, crianças brincando, brinquedos, ambiente seguro e alegre",
    keywords: ["crianças", "educação", "cuidado", "brincadeira", "família"],
  },
  {
    id: "pizza",
    label: "Pizzeria",
    labelPt: "Pizzaria",
    icon: "Pizza",
    primaryColor: "#DC2626",
    secondaryColor: "#EF4444",
    accentColor: "#FBBF24",
    gradient: "from-red-600 to-orange-600",
    tone: "fun",
    sections: [
      { id: "hero", title: "A Melhor Pizza da Cidade", type: "hero", required: true },
      { id: "menu", title: "Sabores", type: "menu", required: true },
      { id: "products", title: "Promoções", type: "products", required: false },
      { id: "features", title: "Diferenciais", type: "features", required: false },
      { id: "gallery", title: "Galeria", type: "gallery", required: false },
      { id: "contact", title: "Delivery", type: "contact", required: true },
    ],
    defaultServices: ["Pizzas Tradicionais", "Pizzas Especiais", "Bordas Recheadas", "Delivery"],
    defaultCTAs: ["Pedir Agora", "Ver Cardápio", "WhatsApp Delivery"],
    imageStyle: "pizza deliciosa saindo do forno, queijo derretido, pizzaria italiana tradicional",
    keywords: ["pizza", "delivery", "sabor", "família", "noite"],
  },
  {
    id: "acai",
    label: "Açaí Shop",
    labelPt: "Açaiteria",
    icon: "IceCream",
    primaryColor: "#7C3AED",
    secondaryColor: "#A78BFA",
    accentColor: "#22C55E",
    gradient: "from-violet-600 to-purple-600",
    tone: "fun",
    sections: [
      { id: "hero", title: "Energia e Sabor", type: "hero", required: true },
      { id: "menu", title: "Cardápio", type: "menu", required: true },
      { id: "products", title: "Combos", type: "products", required: true },
      { id: "features", title: "Toppings", type: "features", required: false },
      { id: "gallery", title: "Galeria", type: "gallery", required: false },
      { id: "contact", title: "Delivery", type: "contact", required: true },
    ],
    defaultServices: ["Açaí na Tigela", "Açaí no Copo", "Vitaminas", "Combos Especiais"],
    defaultCTAs: ["Pedir Agora", "Ver Tamanhos", "Delivery WhatsApp"],
    imageStyle: "açaí na tigela com frutas e granola, ambiente colorido tropical, açaiteria moderna",
    keywords: ["açaí", "energia", "fruta", "saudável", "verão"],
  },
];

export function getBusinessCategory(id: string): BusinessCategory | undefined {
  return businessCategories.find(cat => cat.id === id);
}

export function getBusinessCategoryByOldCategory(oldCategory: string): BusinessCategory | undefined {
  const mappings: Record<string, string> = {
    gastronomy: "restaurant",
    health_beauty: "beauty_salon",
    services: "gym",
    retail: "clothing_store",
    generic: "restaurant",
  };
  return getBusinessCategory(mappings[oldCategory] || oldCategory);
}
